### ISSUE TITLE
Texture replacement bug

### ISSUE THREAD

**Issue by dragonofmercy** [kianzarrin/HideTMPECrosswalks#8]
Hi !
I have some problem with all basic roads only, when I remove the crosswalk it's appear like below:
![crosswalk](https://user-images.githubusercontent.com/140013/75233660-7d3df480-57b9-11ea-9145-1ae0c7ffc1b0.jpg)
Any idea ?
P.S. I have the mass transit DLC

**Comment by originalfoo** [comment]
Are you using any mods that reskin, recolour or otherwise change textures of roads?

**Comment by dragonofmercy** [comment]
The only mod I use is "Road Options (Road Colors Changer ++)" with only "clean textures" parameter

**Comment by dragonofmercy** [comment]
Ok confirmed the problem come when plugin "Road Options (Road Colors Changer ++)" is enabled
https://steamcommunity.com/sharedfiles/filedetails/?id=932192868

**Comment by kianzarrin** [comment]
Do you know how hard is it for mayor to clean the zebra crossings perfectly?! Of-course its going to leave a mark behind! ... just kidding. 

I have made an exception for basic roads not to process APR textures because its not necessary for vanilla roads. I can disable that exception when Road Options (Road Colors Changer ++) is found.

**Comment by kianzarrin** [comment]
I didn't manage to get road options to work but I think my fix will work. it will be in version 3.0

**Comment by kianzarrin** [comment]
![Screenshot (636)](https://user-images.githubusercontent.com/26344691/75628257-de156480-5bdf-11ea-848e-b15cd83bc2cf.png)
